These codes have been taught on [This video](https://www.youtube.com/watch?v=x9JiIFvlUwk&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz) on youtube

# Tensor Indexing

In [2]:
import torch

In [3]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

In [4]:
x[0].shape # x[0. :]

torch.Size([25])

In [5]:
# First feature of all of our examples
x[:, 0]

tensor([0.3905, 0.1150, 0.6475, 0.9791, 0.4653, 0.3139, 0.9247, 0.7935, 0.7389,
        0.7560])

In [6]:
# first 10 features of second batch
x[2, 0: 10]

tensor([0.6475, 0.8993, 0.0664, 0.0215, 0.5617, 0.6683, 0.7211, 0.2860, 0.7558,
        0.7942])

## Fancy indexing

In [7]:
x = torch.arange(10)
indices = [2, 5, 8]
x[indices]

tensor([2, 5, 8])

In [9]:
x = torch.rand(3, 5)
print(x)
print('----')

rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])

# x[1, 4] and x[0, 0]
x[rows, cols]

tensor([[0.7465, 0.4705, 0.1312, 0.3209, 0.4996],
        [0.0706, 0.0561, 0.4085, 0.4577, 0.4607],
        [0.4131, 0.5422, 0.7171, 0.6958, 0.4749]])
----


tensor([0.4607, 0.7465])

## More advanced indexing

In [10]:
x = torch.arange(10)
x[(x < 2) | (x > 8)] 

tensor([0, 1, 9])

In [11]:
x[x.remainder(2) == 0]

tensor([0, 2, 4, 6, 8])

## Useful operations

In [12]:
# if x > 5 then x else x = x * 2
torch.where(x > 5, x, x * 2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [13]:
torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique()

tensor([0, 1, 2, 3, 4])

In [14]:
x.ndimension()

1