These codes have been taught on [This video](https://www.youtube.com/watch?v=x9JiIFvlUwk&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz) on youtube

# Tensor Math & Comparison Operations

In [2]:
import torch

In [3]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8 , 7])

## Addition

In [4]:

z1 = torch.empty(3)
torch.add(x, y, out=z1)
z1

tensor([10., 10., 10.])

In [5]:
z2 = torch.add(x, y)
z2

tensor([10, 10, 10])

In [6]:
z = x + y

## Subtraction

In [8]:
z = x - y
z

tensor([-8, -6, -4])

## Division

In [9]:
# Elementwise divison
z = torch.true_divide(x, y)
z

tensor([0.1111, 0.2500, 0.4286])

In [10]:
z = torch.true_divide(x, 2)
z

tensor([0.5000, 1.0000, 1.5000])

## Inplace operations

In [11]:
# Operations followed by _ are inplace
t = torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

## Exponentiation

In [12]:
z = x.pow(2)
z

tensor([1, 4, 9])

In [14]:
z = x ** 2
z

tensor([1, 4, 9])

## Simple comparison

In [15]:
z = x > 0
z

tensor([True, True, True])

In [16]:
z = x < 0
z

tensor([False, False, False])

## Matrix multipication

In [17]:
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))

x3 = torch.mm(x1, x2)
x3

tensor([[1.1381, 1.1120, 1.4112],
        [0.6808, 0.6395, 0.6942]])

In [18]:
x3 = x1.mm(x2)
x3

tensor([[1.1381, 1.1120, 1.4112],
        [0.6808, 0.6395, 0.6942]])

## Matrix exponentiation

In [22]:
matrix_exp = torch.rand(5, 5)
matrix_exp.matrix_power(3)
matrix_exp

tensor([[0.3156, 0.2648, 0.7706, 0.4230, 0.4259],
        [0.4837, 0.3641, 0.1391, 0.1657, 0.8435],
        [0.2095, 0.9832, 0.1679, 0.1442, 0.2927],
        [0.8234, 0.4831, 0.6300, 0.0433, 0.4268],
        [0.6540, 0.2661, 0.9313, 0.2886, 0.3455]])

## Elementwise multiplication

In [24]:
x

tensor([1, 2, 3])

In [25]:
y

tensor([9, 8, 7])

In [23]:
z = x * y
z

tensor([ 9, 16, 21])

## Dot product

In [26]:
# Sum of elementwise multiplication
z = torch.dot(x, y)
z

tensor(46)

 ## Batch Matrix Multiplication

In [ ]:
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))