These codes have been taught on [This video](https://www.youtube.com/watch?v=x9JiIFvlUwk&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz) on youtube

# Initializing Tensor

In [1]:
import torch

In [2]:
# Simple tensor
my_tensor = torch.tensor([[1, 2, 3],
                          [4, 5, 6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
# Tensor with dtype
my_tensor = torch.tensor([[1, 2, 3],
                          [4, 5, 6]], dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
# Tensor using cuda if available
device = "cuda" if torch.cuda.is_available() else "cpu"

my_tensor = torch.tensor([[1, 2, 3],
                          [4, 5, 6]], device=device)
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
# getting dtype
my_tensor.dtype

torch.int64

In [6]:
# getting device
my_tensor.device

device(type='cpu')

In [7]:
# getting the shape
my_tensor.shape

torch.Size([2, 3])

In [9]:
# check if requires gradient or not
my_tensor.requires_grad

False

## Other common initialization methods

In [11]:
x = torch.empty(size=(3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
x = torch.zeros((3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
# Random uniform distribution in [0, 1]
x = torch.rand((3, 3))
x

tensor([[0.9917, 0.3275, 0.6611],
        [0.1659, 0.5960, 0.6328],
        [0.4521, 0.0510, 0.5575]])

In [14]:
x = torch.ones((3, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# Indentity matrix, be careful about the parameters it is not a tuple unlike the others
X = torch.eye(3, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [24]:
# Here step means the difference between two elements
x = torch.arange(start=0, end=5, step=1)
x

tensor([0, 1, 2, 3, 4])

In [21]:
# Here steps means total number of elements
x = torch.linspace(start=0.1, end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [25]:
# Normal Distribution
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
x

tensor([[-1.1391, -0.5696,  0.8662, -0.6698, -1.3572]])

In [28]:
# Uniform distribution
x = torch.empty(size=(1, 5)).uniform_(0, 1)
x

tensor([[0.3565, 0.0894, 0.1243, 0.5341, 0.9018]])

In [29]:
x = torch.diag(torch.ones(3))
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## How to initialize and convert tensors to other types (int, float, double)

In [32]:
tensor = torch.arange(4)
tensor.bool()

tensor([False,  True,  True,  True])

In [33]:
# Convert to int16
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [34]:
# Convert to int64
tensor.long()

tensor([0, 1, 2, 3])

In [35]:
# Convert to float16
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [36]:
# Convert to float32
tensor.float()

tensor([0., 1., 2., 3.])

In [37]:
# Convert to float64
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

## Array to tensor conversion and vice-versa

In [38]:
import numpy as np
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [39]:
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])